# Site
name: 'Data Gatherers'
description: 'Data gatherers are a group of highly motivated data scientists trying to change the world.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'thedatagathering@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    wale:
      name:           Wale
      site:           https://www.waleopakunle.com
      avatar:         /assets/images/wale.jpg
      bio:            "Hi, I am Wale. I am a data scientist, data engineer, data analyst and software developer. I love building intelligent applications"
      email:          opakunlejo@gmail.com
      twitter:        https://twitter.com/__opa_

    ore:
      name:           Ore
      site:           https://www.waleopakunle.com
      avatar:         /assets/images/wale.jpg
      bio:            "Hi, I am Wale. I am a data scientist, data engineer, data analyst and software developer. I love building intelligent applications"
      email:          opakunlejo@gmail.com
      twitter:        https://twitter.com/__opa_

    morenikeji:
      name:           Morenikeji
      site:           https://www.waleopakunle.com
      avatar:         /assets/images/wale.jpg
      bio:            "Hi, I am Wale. I am a data scientist, data engineer, data analyst and software developer. I love building intelligent applications"
      email:          opakunlejo@gmail.com
      twitter:        https://twitter.com/__opa_

    tunde:
      name:           Tunde
      site:           https://www.waleopakunle.com
      avatar:         /assets/images/wale.jpg
      bio:            "Hi, I am Wale. I am a data scientist, data engineer, data analyst and software developer. I love building intelligent applications"
      email:          opakunlejo@gmail.com
      twitter:        https://twitter.com/__opa_

    samuel:
      name:           Samuel
      site:           https://www.waleopakunle.com
      avatar:         /assets/images/wale.jpg
      bio:            "Hi, I am Wale. I am a data scientist, data engineer, data analyst and software developer. I love building intelligent applications"
      email:          opakunlejo@gmail.com
      twitter:        https://twitter.com/__opa_

    kenneth:
      name:           Kenneth
      site:           https://www.waleopakunle.com
      avatar:         /assets/images/wale.jpg
      bio:            "Hi, I am Wale. I am a data scientist, data engineer, data analyst and software developer. I love building intelligent applications"
      email:          opakunlejo@gmail.com
      twitter:        https://twitter.com/__opa_

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: wale
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]